version: "3.3"

services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456 
    ports:
      - '5432:5432'
    volumes: 
      - ./temp-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql