DROP DATABASE IF EXISTS lbc_db;

CREATE DATABASE lbc_db;

\c lbc_db

CREATE TABLE fizzbuzz (
    id  BIGSERIAL PRIMARY KEY NOT NULL,
    creation_date TIMESTAMP WITH TIME ZONE  DEFAULT NOW() NOT NULL,
    last_update TIMESTAMP WITH TIME ZONE  DEFAULT NOW() NOT NULL
);